/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wealoha_libcurldroid_Curl */

#ifndef _Included_com_wealoha_libcurldroid_Curl
#define _Included_com_wealoha_libcurldroid_Curl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wealoha_libcurldroid_Curl
 * Method:    curlGlobalInitNative
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_wealoha_libcurldroid_Curl_curlGlobalInitNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wealoha_libcurldroid_Curl
 * Method:    curlGlobalCleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wealoha_libcurldroid_Curl_curlGlobalCleanup
  (JNIEnv *, jobject);

/*
 * Class:     com_wealoha_libcurldroid_Curl
 * Method:    curlEasyInitNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wealoha_libcurldroid_Curl_curlEasyInitNative
  (JNIEnv *, jobject);

/*
 * Class:     com_wealoha_libcurldroid_Curl
 * Method:    curlEasyCleanupNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wealoha_libcurldroid_Curl_curlEasyCleanupNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wealoha_libcurldroid_Curl
 * Method:    curlEasySetoptLongNative
 * Signature: (JIJ)I
 */
JNIEXPORT jint JNICALL Java_com_wealoha_libcurldroid_Curl_curlEasySetoptLongNative
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     com_wealoha_libcurldroid_Curl
 * Method:    curlEasySetoptFunctionNative
 * Signature: (JILcom/wealoha/libcurldroid/Curl/Callback;)I
 */
JNIEXPORT jint JNICALL Java_com_wealoha_libcurldroid_Curl_curlEasySetoptFunctionNative
  (JNIEnv *, jobject, jlong, jint, jobject);

/*
 * Class:     com_wealoha_libcurldroid_Curl
 * Method:    curlEasySetoptObjectPointNative
 * Signature: (JILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_wealoha_libcurldroid_Curl_curlEasySetoptObjectPointNative
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     com_wealoha_libcurldroid_Curl
 * Method:    curlEasyPerformNavite
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_wealoha_libcurldroid_Curl_curlEasyPerformNavite
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_wealoha_libcurldroid_Curl_Callback */

#ifndef _Included_com_wealoha_libcurldroid_Curl_Callback
#define _Included_com_wealoha_libcurldroid_Curl_Callback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
